### PR TITLE
feat(advanced): add geojson modelica translator links

### PR DESCRIPTION
**Pull request by macintoshpie**
### Addresses
https://github.com/urbanopt/geojson-modelica-translator/issues/130
### Pull Request Description

Add links to GMT project github and documentation

### CODE REVIEW

**Comment by macintoshpie** [comment]
@nllong @vtnate I don't have permission to request reviewers so tagging here

**Comment by nllong** [comment]
@macintoshpie you should now. write access granted.

**Review by kflemin — APPROVED** [review]
can you make this PR against september-release branch instead of develop? thanks!

**Comment by macintoshpie** [comment]
@kflemin I updated the base branch, if it looks good to you I think we're good to merge 👍

**Comment by nllong** [comment]
Thanks everyone for making this happen so fast!

**Pull request merged**
